name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build APK
        run: |
          sudo chmod -R 777 .
          docker pull kivy/buildozer
          docker run --rm -v ${{ github.workspace }}:/home/user/hostcwd kivy/buildozer bash -c "yes | buildozer android debug"
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
